import { useState, useEffect, useCallback } from "react";
const API = "http://localhost:3000/api";
const css = `
  @import url('https://fonts.googleapis.com/css2?family=Share+Tech+Mono&family=Rajdhani:wght@400;600;700&display=swap');
  *,*::before,*::after{box-sizing:border-box;margin:0;padding:0}
  :root{--bg:#080c10;--surface:#0d1117;--surface2:#161b22;--border:#21262d;--accent:#00ff88;--accent2:#00cfff;--danger:#ff4444;--warn:#ffaa00;--text:#e6edf3;--muted:#8b949e;--mono:'Share Tech Mono',monospace;--ui:'Rajdhani',sans-serif}
  body{background:var(--bg);color:var(--text);font-family:var(--ui);min-height:100vh}
  body::before{content:'';position:fixed;inset:0;background:repeating-linear-gradient(0deg,transparent,transparent 2px,rgba(0,255,136,.015) 2px,rgba(0,255,136,.015) 4px);pointer-events:none;z-index:9999}
  .layout{display:grid;grid-template-columns:220px 1fr;grid-template-rows:56px 1fr;min-height:100vh}
  .topbar{grid-column:1/-1;background:var(--surface);border-bottom:1px solid var(--border);display:flex;align-items:center;padding:0 24px;gap:16px;position:sticky;top:0;z-index:100}
  .logo{font-family:var(--mono);font-size:15px;color:var(--accent);letter-spacing:2px}.logo span{color:var(--muted)}
  .topbar-right{margin-left:auto;display:flex;align-items:center;gap:8px;font-size:13px;font-family:var(--mono)}
  .dot{width:8px;height:8px;border-radius:50%}.dot.on{background:var(--accent);box-shadow:0 0 8px var(--accent);animation:pulse 2s infinite}.dot.off{background:var(--danger)}
  @keyframes pulse{0%,100%{opacity:1}50%{opacity:.4}}
  .sidebar{background:var(--surface);border-right:1px solid var(--border);padding:20px 0;display:flex;flex-direction:column;gap:4px}
  .nav-item{display:flex;align-items:center;gap:10px;padding:10px 20px;cursor:pointer;font-size:14px;font-weight:600;letter-spacing:1px;text-transform:uppercase;color:var(--muted);border-left:3px solid transparent;background:none;border-top:none;border-right:none;border-bottom:none;width:100%;text-align:left;font-family:var(--ui);transition:all .15s}
  .nav-item:hover{color:var(--text);background:rgba(255,255,255,.03)}.nav-item.active{color:var(--accent);border-left-color:var(--accent);background:rgba(0,255,136,.05)}
  .main{padding:28px;overflow-y:auto;background:radial-gradient(ellipse 60% 40% at 80% 10%,rgba(0,207,255,.04) 0%,transparent 60%),var(--bg)}
  .page-title{font-size:28px;font-weight:700;letter-spacing:2px;text-transform:uppercase;margin-bottom:24px}.page-title span{color:var(--accent)}
  .grid-4{display:grid;grid-template-columns:repeat(4,1fr);gap:16px;margin-bottom:24px}
  .grid-2{display:grid;grid-template-columns:repeat(2,1fr);gap:16px}.grid-3{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}
  .card{background:var(--surface);border:1px solid var(--border);border-radius:8px;padding:20px;position:relative;overflow:hidden}
  .card::before{content:'';position:absolute;top:0;left:0;right:0;height:2px;background:linear-gradient(90deg,transparent,var(--accent),transparent);opacity:.3}
  .card.blue::before{background:linear-gradient(90deg,transparent,var(--accent2),transparent)}.card.red::before{background:linear-gradient(90deg,transparent,var(--danger),transparent)}.card.warn::before{background:linear-gradient(90deg,transparent,var(--warn),transparent)}
  .stat-label{font-size:11px;font-family:var(--mono);color:var(--muted);letter-spacing:2px;text-transform:uppercase;margin-bottom:8px}
  .stat-value{font-size:36px;font-weight:700;font-family:var(--mono);color:var(--accent);line-height:1}
  .stat-value.b{color:var(--accent2)}.stat-value.r{color:var(--danger)}.stat-value.w{color:var(--warn)}
  .stat-sub{font-size:12px;color:var(--muted);margin-top:6px;font-family:var(--mono)}
  .btn{display:inline-flex;align-items:center;gap:8px;padding:9px 18px;border-radius:6px;font-family:var(--ui);font-size:13px;font-weight:600;letter-spacing:1px;text-transform:uppercase;cursor:pointer;border:1px solid;transition:all .15s}
  .btn-p{background:rgba(0,255,136,.1);border-color:var(--accent);color:var(--accent)}.btn-p:hover{background:rgba(0,255,136,.2)}
  .btn-d{background:rgba(255,68,68,.1);border-color:var(--danger);color:var(--danger)}.btn-d:hover{background:rgba(255,68,68,.2)}
  .btn-w{background:rgba(255,170,0,.1);border-color:var(--warn);color:var(--warn)}.btn-w:hover{background:rgba(255,170,0,.2)}
  .btn-g{background:transparent;border-color:var(--border);color:var(--muted)}.btn-g:hover{border-color:var(--muted);color:var(--text)}
  .btn:disabled{opacity:.4;cursor:not-allowed}.btn-sm{padding:5px 12px;font-size:11px}
  table{width:100%;border-collapse:collapse;font-size:13px}thead tr{border-bottom:1px solid var(--border)}
  th{text-align:left;padding:10px 14px;font-size:11px;font-family:var(--mono);color:var(--muted);letter-spacing:2px;text-transform:uppercase;font-weight:400}
  td{padding:11px 14px;border-bottom:1px solid rgba(33,38,45,.6);font-family:var(--mono);font-size:13px}
  tr:hover td{background:rgba(255,255,255,.02)}tr:last-child td{border-bottom:none}
  .badge{display:inline-block;padding:2px 8px;border-radius:4px;font-size:11px;font-family:var(--mono);letter-spacing:1px}
  .bg{background:rgba(0,255,136,.1);color:var(--accent);border:1px solid rgba(0,255,136,.3)}.bb{background:rgba(0,207,255,.1);color:var(--accent2);border:1px solid rgba(0,207,255,.3)}.bx{background:rgba(139,148,158,.1);color:var(--muted);border:1px solid rgba(139,148,158,.3)}
  .arena-card{background:var(--surface);border:1px solid var(--border);border-radius:8px;padding:18px;display:flex;flex-direction:column;gap:14px}
  .arena-name{font-size:16px;font-weight:700;letter-spacing:2px;text-transform:uppercase;font-family:var(--mono)}
  .arena-players{font-size:24px;font-weight:700;font-family:var(--mono);color:var(--accent2)}.arena-players span{font-size:14px;color:var(--muted)}
  .bar{height:4px;background:var(--border);border-radius:2px;overflow:hidden}.bar-fill{height:100%;border-radius:2px;background:linear-gradient(90deg,var(--accent2),var(--accent));transition:width .5s}
  .prow{display:flex;align-items:center;gap:12px;padding:10px 0;border-bottom:1px solid var(--border)}.prow:last-child{border-bottom:none}
  .pav{width:32px;height:32px;background:var(--surface2);border-radius:4px;display:flex;align-items:center;justify-content:center;font-size:14px;border:1px solid var(--border)}
  .pname{font-family:var(--mono);font-size:13px;flex:1}.parena{font-size:11px;color:var(--muted);font-family:var(--mono)}
  .sh{display:flex;align-items:center;justify-content:space-between;margin-bottom:16px}
  .st{font-size:14px;font-weight:600;letter-spacing:2px;text-transform:uppercase;color:var(--muted);font-family:var(--mono)}
  .empty{text-align:center;padding:40px;color:var(--muted);font-family:var(--mono);font-size:13px}
  .toast-box{position:fixed;bottom:24px;right:24px;display:flex;flex-direction:column;gap:8px;z-index:9998}
  .toast{padding:12px 18px;border-radius:6px;font-family:var(--mono);font-size:13px;border:1px solid;display:flex;align-items:center;gap:8px;animation:si .2s ease}
  .ts{background:rgba(0,255,136,.1);border-color:var(--accent);color:var(--accent)}.te{background:rgba(255,68,68,.1);border-color:var(--danger);color:var(--danger)}
  @keyframes si{from{transform:translateX(100%);opacity:0}to{transform:translateX(0);opacity:1}}
  .overlay{position:fixed;inset:0;background:rgba(0,0,0,.7);display:flex;align-items:center;justify-content:center;z-index:1000;backdrop-filter:blur(4px)}
  .confirm{background:var(--surface);border:1px solid var(--border);border-radius:10px;padding:28px;max-width:380px;width:90%}
  .confirm-title{font-size:18px;font-weight:700;margin-bottom:10px}.confirm-msg{color:var(--muted);font-size:14px;margin-bottom:20px;font-family:var(--mono)}
  .confirm-btns{display:flex;gap:10px;justify-content:flex-end}
  .rank1{color:#ffd700}.rank2{color:#c0c0c0}.rank3{color:#cd7f32}
`;
const tAgo=d=>{if(!d)return'—';const s=Math.floor((Date.now()-new Date(d))/1000);return s<60?`${s}s`:s<3600?`${Math.floor(s/60)}m`:`${Math.floor(s/3600)}h`;};
const Toasts=({t})=><div className="toast-box">{t.map(x=><div key={x.id} className={`toast ${x.type==='success'?'ts':'te'}`}>{x.type==='success'?'✓':'✗'} {x.message}</div>)}</div>;
const Confirm=({msg,ok,cancel})=><div className="overlay" onClick={cancel}><div className="confirm" onClick={e=>e.stopPropagation()}><div className="confirm-title">⚠ Confirmar</div><div className="confirm-msg">{msg}</div><div className="confirm-btns"><button className="btn btn-g" onClick={cancel}>Cancelar</button><button className="btn btn-d" onClick={ok}>Confirmar</button></div></div></div>;
function Dashboard({status,overview}){return<div><div className="page-title">Panel <span>Admin</span></div><div className="grid-4"><div className="card"><div className="stat-label">Online</div><div className="stat-value">{status?.players?.length??'—'}</div><div className="stat-sub">{status?.online?'activo':'offline'}</div></div><div className="card blue"><div className="stat-label">Jugadores</div><div className="stat-value b">{overview?.totalPlayers??'—'}</div><div className="stat-sub">registrados</div></div><div className="card warn"><div className="stat-label">Partidas</div><div className="stat-value w">{overview?.totalGames??'—'}</div><div className="stat-sub">historial</div></div><div className="card red"><div className="stat-label">Muertes</div><div className="stat-value r">{overview?.totalDeaths??'—'}</div><div className="stat-sub">en BD</div></div></div><div className="grid-2"><div className="card"><div className="sh"><div className="st">Arenas</div></div>{status?.arenas?.length>0?status.arenas.map(a=><div key={a.name} className="prow"><div className="pav">🗺</div><div><div className="pname">{a.name}</div><div className="parena">{a.players}/{a.maxPlayers}</div></div><span className={`badge ${a.status==='PLAYING'?'bg':'bb'}`}>{a.status||'WAITING'}</span></div>):<div className="empty">Sin datos</div>}</div><div className="card"><div className="sh"><div className="st">Conectados</div><span className="badge bg">{status?.players?.length??0} online</span></div>{status?.players?.length>0?status.players.slice(0,8).map(p=><div key={p.name} className="prow"><div className="pav">👤</div><div className="pname">{p.name}</div><div className="parena">{p.arena||'lobby'}</div></div>):<div className="empty">Sin jugadores</div>}</div></div></div>;}
function Arenas({status,addToast}){const[ld,setLd]=useState({});const[cf,setCf]=useState(null);const act=async(k,u)=>{setLd(l=>({...l,[k]:true}));try{const r=await fetch(u,{method:'POST'});const d=await r.json();addToast(d.message||'OK','success');}catch{addToast('Error','error');}setLd(l=>({...l,[k]:false}));setCf(null);};const arenas=status?.arenas?.length>0?status.arenas:[{name:'arena1',players:0,maxPlayers:8,status:'WAITING'},{name:'arena2',players:0,maxPlayers:8,status:'WAITING'}];return<div><div className="page-title">Arenas <span>Control</span></div><div style={{marginBottom:20}}><button className="btn btn-d" onClick={()=>setCf({msg:'¿Resetear TODAS?',fn:()=>act('all',`${API}/admin/reset-all`)})}>🔄 Resetear todas</button></div><div className="grid-3">{arenas.map(a=><div key={a.name} className="arena-card"><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><div className="arena-name">{a.name}</div><span className={`badge ${a.status==='PLAYING'?'bg':'bx'}`}>{a.status||'WAITING'}</span></div><div><div className="arena-players">{a.players??0}<span>/{a.maxPlayers??'?'}</span></div><div className="bar" style={{marginTop:8}}><div className="bar-fill" style={{width:`${a.maxPlayers?(a.players/a.maxPlayers*100):0}%`}}/></div></div><div style={{display:'flex',gap:8}}><button className="btn btn-p btn-sm" onClick={()=>act(`s${a.name}`,`${API}/admin/start/${a.name}`)}>▶</button><button className="btn btn-w btn-sm" onClick={()=>act(`x${a.name}`,`${API}/admin/stop/${a.name}`)}>■</button><button className="btn btn-d btn-sm" onClick={()=>setCf({msg:`¿Resetear ${a.name}?`,fn:()=>act(`r${a.name}`,`${API}/admin/reset-arena/${a.name}`)})}>🔄</button></div></div>)}</div>{cf&&<Confirm msg={cf.msg} ok={cf.fn} cancel={()=>setCf(null)}/>}</div>;}
function Players({status,addToast}){const[cf,setCf]=useState(null);const kick=async n=>{try{await fetch(`${API}/admin/kick/${n}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({reason:'Kicked by admin'})});addToast(`${n} kickeado`,'success');}catch{addToast('Error','error');}setCf(null);};const players=status?.players||[];return<div><div className="page-title">Jugadores <span>Online</span></div><div className="card"><div className="sh"><div className="st">{players.length} conectados</div></div>{players.length>0?<table><thead><tr><th>Jugador</th><th>Arena</th><th>Estado</th><th>Acción</th></tr></thead><tbody>{players.map(p=><tr key={p.name}><td><div style={{display:'flex',alignItems:'center',gap:8}}><div className="pav">👤</div>{p.name}</div></td><td>{p.arena||<span className="badge bx">lobby</span>}</td><td><span className="badge bg">online</span></td><td><button className="btn btn-d btn-sm" onClick={()=>setCf(p.name)}>Kick</button></td></tr>)}</tbody></table>:<div className="empty">Sin jugadores</div>}</div>{cf&&<Confirm msg={`¿Kickear a ${cf}?`} ok={()=>kick(cf)} cancel={()=>setCf(null)}/>}</div>;}
function Stats({addToast}){const[lb,setLb]=useState([]);const[d,setD]=useState([]);const[tab,setTab]=useState('lb');const load=useCallback(async()=>{try{const[l,x]=await Promise.all([fetch(`${API}/stats/leaderboard`).then(r=>r.json()),fetch(`${API}/stats/recent-deaths`).then(r=>r.json())]);setLb(Array.isArray(l)?l:[]);setD(Array.isArray(x)?x:[]);}catch{addToast('Error','error');}},[]);useEffect(()=>{load();},[load]);return<div><div className="page-title">Stats <span>Globales</span></div><div style={{display:'flex',gap:8,marginBottom:20}}><button className={`btn ${tab==='lb'?'btn-p':'btn-g'}`} onClick={()=>setTab('lb')}>🏆 Leaderboard</button><button className={`btn ${tab==='d'?'btn-p':'btn-g'}`} onClick={()=>setTab('d')}>💀 Muertes</button><button className="btn btn-g" style={{marginLeft:'auto'}} onClick={load}>↻</button></div>{tab==='lb'&&<div className="card"><table><thead><tr><th>#</th><th>Jugador</th><th>Kills</th><th>Muertes</th><th>K/D</th><th>Wins</th></tr></thead><tbody>{lb.length>0?lb.map((p,i)=><tr key={p.player_name}><td className={i===0?'rank1':i===1?'rank2':i===2?'rank3':''}>{i===0?'🥇':i===1?'🥈':i===2?'🥉':`#${i+1}`}</td><td>{p.player_name}</td><td style={{color:'var(--accent)'}}>{p.kills}</td><td style={{color:'var(--danger)'}}>{p.deaths}</td><td style={{color:'var(--accent2)'}}>{p.kd_ratio}</td><td style={{color:'var(--warn)'}}>{p.wins}</td></tr>):<tr><td colSpan={6}><div className="empty">Sin datos</div></td></tr>}</tbody></table></div>}{tab==='d'&&<div className="card"><table><thead><tr><th>Jugador</th><th>Killer</th><th>Arena</th><th>Items</th><th>Cuándo</th></tr></thead><tbody>{d.length>0?d.map((x,i)=><tr key={i}><td style={{color:'var(--danger)'}}>💀 {x.player_name}</td><td>{x.killer==='void'?<span className="badge bx">void</span>:<span style={{color:'var(--accent)'}}>⚔ {x.killer}</span>}</td><td><span className="badge bb">{x.game_name}</span></td><td style={{color:'var(--muted)',fontSize:11}}>{Array.isArray(x.items_lost)&&x.items_lost.length>0?x.items_lost.slice(0,3).map(it=>`${it.item}x${it.quantity}`).join(', '):'—'}</td><td style={{color:'var(--muted)'}}>{tAgo(x.created_at)}</td></tr>):<tr><td colSpan={5}><div className="empty">Sin muertes</div></td></tr>}</tbody></table></div>}</div>;}
export default function App(){const[page,setPage]=useState('dashboard');const[status,setStatus]=useState(null);const[overview,setOverview]=useState(null);const[toasts,setToasts]=useState([]);const addToast=useCallback((message,type='success')=>{const id=Date.now();setToasts(t=>[...t,{id,message,type}]);setTimeout(()=>setToasts(t=>t.filter(x=>x.id!==id)),3000);},[]);useEffect(()=>{const f=async()=>{try{const[s,o]=await Promise.all([fetch(`${API}/status`).then(r=>r.json()),fetch(`${API}/stats/overview`).then(r=>r.json())]);setStatus(s);setOverview(o);}catch{setStatus({online:false,players:[],arenas:[]});}};f();const i=setInterval(f,5000);return()=>clearInterval(i);},[]);const nav=[{id:'dashboard',icon:'▦',label:'Dashboard'},{id:'arenas',icon:'🗺',label:'Arenas'},{id:'players',icon:'👥',label:'Jugadores'},{id:'stats',icon:'📊',label:'Stats'}];return<><style>{css}</style><div className="layout"><header className="topbar"><div className="logo">Sky<span>Wars</span> · Admin</div><div className="topbar-right"><div className={`dot ${status?.online?'on':'off'}`}/>{status?.online?'ONLINE':'OFFLINE'}{status?.lastUpdate&&<span style={{color:'var(--muted)',marginLeft:8}}>· {tAgo(status.lastUpdate)}</span>}</div></header><nav className="sidebar">{nav.map(n=><button key={n.id} className={`nav-item ${page===n.id?'active':''}`} onClick={()=>setPage(n.id)}><span>{n.icon}</span>{n.label}</button>)}</nav><main className="main">{page==='dashboard'&&<Dashboard status={status} overview={overview}/>}{page==='arenas'&&<Arenas status={status} addToast={addToast}/>}{page==='players'&&<Players status={status} addToast={addToast}/>}{page==='stats'&&<Stats addToast={addToast}/>}</main></div><Toasts t={toasts}/></>;};
